# Generated by Django 4.1.7 on 2023-05-07 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 16, 40, 25, 836394)),
        ),
    ]
