# Generated by Django 4.1.7 on 2023-05-13 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_askquestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 11, 44, 40, 736975)),
        ),
    ]
