# Generated by Django 4.1.7 on 2023-06-01 09:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_alter_askquestion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 15, 21, 50, 932372)),
        ),
    ]
