# Generated by Django 4.1.7 on 2023-06-02 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_members_added_alter_askquestion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 10, 59, 49, 750422)),
        ),
    ]
