# Generated by Django 4.1.7 on 2023-06-02 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_group_count_alter_askquestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 19, 17, 3, 758970)),
        ),
        migrations.AlterField(
            model_name='group',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
