# Generated by Django 4.1.7 on 2023-06-02 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_alter_askquestion_time_alter_group_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 19, 27, 25, 964722)),
        ),
    ]
