# Generated by Django 4.1.7 on 2023-06-05 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_alter_askquestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 14, 33, 31, 485433)),
        ),
    ]
