# Generated by Django 4.1.7 on 2023-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedlike',
            name='visited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='visited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
