# Generated by Django 4.1.7 on 2023-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_askedlike_visited_like_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedlike',
            name='source',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='like',
            name='source',
            field=models.CharField(default='ik', max_length=100),
        ),
    ]
