# Generated by Django 4.1.7 on 2023-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_askedlike_source_like_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedlike',
            name='revealed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='askedlike',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
