# Generated by Django 4.1.7 on 2023-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_askedlike_revealed_alter_askedlike_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedlike',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
