# Generated by Django 4.1.7 on 2023-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_askedlike_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
