# Generated by Django 4.1.7 on 2023-05-07 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_time', models.DateField(blank=True, null=True)),
                ('paid', models.CharField(default='False', max_length=200)),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 7, 14, 29, 41, 888943), null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('total_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
