# Generated by Django 4.1.7 on 2023-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paid_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='reveal',
            field=models.IntegerField(default=0),
        ),
    ]
