# Generated by Django 4.1.7 on 2023-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_reveal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
